# Generated by Django 2.1.5 on 2019-01-23 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.CharField(default='rff', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Drafts',
            fields=[
                ('MailBox_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emailapps.MailBox')),
            ],
            bases=('emailapps.MailBox',),
        ),
    ]
