# Generated by Django 2.0.9 on 2019-01-22 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='outbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailapps.mail')),
            ],
        ),
    ]
