# Generated by Django 2.1.5 on 2019-01-24 16:00

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('emailapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('mailbox_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emailapps.MailBox')),
            ],
            bases=('emailapps.mailbox',),
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('mailbox_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emailapps.MailBox')),
            ],
            bases=('emailapps.mailbox',),
        ),
        migrations.CreateModel(
            name='ReplyTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=500, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('mailbox_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emailapps.MailBox')),
            ],
            bases=('emailapps.mailbox',),
        ),
        migrations.RenameField(
            model_name='drafts',
            old_name='MailBox_ptr',
            new_name='mailbox_ptr',
        ),
        migrations.RemoveField(
            model_name='mailbox',
            name='check',
        ),
        migrations.AddField(
            model_name='mailbox',
            name='cc',
            field=models.CharField(default=[], max_length=10000),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='message',
            field=models.TextField(default='', max_length=1000000000),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='recepient',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='sender',
            field=models.EmailField(default=django.contrib.auth.models.User, editable=False, max_length=254),
        ),
        migrations.AddField(
            model_name='replyto',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='emailapps.MailBox'),
        ),
        migrations.AddField(
            model_name='replyto',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='emailapps.ReplyTo'),
        ),
    ]
