# Generated by Django 2.1.5 on 2019-01-23 17:24

from django.db import migrations, models
import emailapps.views


class Migration(migrations.Migration):

    dependencies = [
        ('emailapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailcompose',
            name='cc',
            field=models.CharField(default=[], max_length=10000),
        ),
        migrations.AddField(
            model_name='mailcompose',
            name='message',
            field=models.TextField(default='', max_length=1000000000),
        ),
        migrations.AddField(
            model_name='mailcompose',
            name='recepient',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mailcompose',
            name='sender',
            field=models.EmailField(default="", editable=False, max_length=254),
        ),
    ]
