# Generated by Django 2.1.5 on 2019-01-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailapps', '0002_auto_20190124_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inbox',
            new_name='Inboxs',
        ),
    ]
