# Generated by Django 2.1.5 on 2019-01-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapps', '0003_auto_20190124_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='attachment',
            field=models.FileField(default='ire.txt', upload_to=''),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='subject',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
