# Generated by Django 2.0.9 on 2019-01-23 05:21

from django.db import migrations, models
import emailapps.views


class Migration(migrations.Migration):

    dependencies = [
        ('emailapps', '0003_mailingadrress'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='cc',
            field=models.CharField(default=[], max_length=100000000),
        ),
        migrations.AddField(
            model_name='mail',
            name='mail',
            field=models.TextField(default='', max_length=1000000000),
        ),
        migrations.AddField(
            model_name='mail',
            name='recepient',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mail',
            name='sender',
            field=models.EmailField(default=emailapps.views.sentmails, editable=False, max_length=254),
        ),
    ]
