# Generated by Django 2.1.5 on 2019-01-24 10:24

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapps', '0004_outbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailcompose',
            name='sender',
            field=models.EmailField(default=django.contrib.auth.models.User, editable=False, max_length=254),
        ),
    ]
