# Generated by Django 2.1.5 on 2019-01-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailapps', '0006_replyto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replyto',
            old_name='post',
            new_name='message',
        ),
    ]
