# Generated by Django 2.1.5 on 2019-01-24 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailapps', '0007_auto_20190124_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('mailcompose_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emailapps.MailCompose')),
            ],
            bases=('emailapps.mailcompose',),
        ),
    ]
